
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # 1. 레포지토리 체크아웃
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: add ssh key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}
          
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/SNS_Server   # 서버에서 프로젝트가 있는 경로로 이동
            git pull origin main       # main 브랜치의 최신 코드 pull
            npm install                # 필요하다면 종속성 설치
            npx pm2 restart app            # PM2로 실행 중인 앱 재시작
          EOF

